---
title: "LMR with gam"
author: "Remko Duursma"
date: "Friday, September 05, 2014"
output: html_document
---
  
  
```{r init, echo=FALSE}
library(knitr)
opts_knit$set(root.dir=normalizePath('../'))
opts_chunk$set(echo=FALSE, warning=FALSE, error=FALSE, message=FALSE)
```


```{r load}

library(mgcv)
library(plantecophys)
library(reshape2)

source("load.R")
source("R/prepareDataset.R")
```


```{r functions}

fitgam <- function(X,Y,dfr, k=-1, model=1){
  dfr$Y <- dfr[,Y]
  dfr$X <- dfr[,X]
  dfr <- droplevels(dfr)
  g<- gam(Y ~ s(X, k=k), data=dfr)
  
  return(g)
}
addpoly <- function(x,y1,y2,col=alpha("lightgrey",0.8),...){
  ii <- order(x)
  y1 <- y1[ii]
  y2 <- y2[ii]
  x <- x[ii]
  polygon(c(x,rev(x)), c(y1, rev(y2)), col=col, border=NA,...)
}


gamplotandpred <- function(dat, pftvar, yvar, Hs = c(1,10)){
  
  o <- par()
  dat$PFT <- dat[,pftvar]
  dat$Y <- dat[,yvar]
  dat <- droplevels(subset(dat, !is.na(lh.t) & !is.na(Y)))
  
  d <- split(dat, dat$PFT)
  
  hran <- lapply(d, function(x)range(x$lh.t, na.rm=TRUE))
  fits <- lapply(d, function(x)fitgam("lh.t","Y",x, k=4))
  pred <- lapply(fits, function(x)predict(x, newdata=data.frame(X=log10(Hs)), 
                                          se.fit=TRUE))
  
  
  palette(rainbow(nlevels(dat$PFT)))
  
  with(dat, plot(lh.t, Y, axes=FALSE, pch=16, col=PFT, ylab=yvar))
  magaxis(side=1:2, unlog=1:2)
  
  for(i in 1:length(d)){
    nd <- data.frame(X=seq(hran[[i]][1], hran[[i]][2], length=101))
    p <- predict(fits[[i]],nd,se.fit=TRUE)
    addpoly(nd$X, p$fit-2*p$se.fit, p$fit+2*p$se.fit, col=alpha("lightgrey",0.7))
    lines(nd$X, p$fit, col=palette()[i], lwd=2)
  }
  abline(v=log10(Hs), col="dimgrey", lty=5)
  legend("bottomleft", levels(dat$PFT), fill=palette(), cex=0.7)
  
  
  logY <- sapply(pred, "[[", "fit")
  se <- sapply(pred, "[[", "se.fit")
  Y_cil <- 10^(logY - 2*se)
  Y_ciu <- 10^(logY + 2*se)
  Y <- 10^logY
  
  
  
  par(mar=c(7,5,2,2), las=2)
  b <- barplot2(Y[1,], beside=T, plot.ci=TRUE, ci.l=Y_cil[1,], ci.u=Y_ciu[1,],
                main=paste0("Height = ",Hs[1],"m"), col=palette(), ylab=yvar)
  
  b <- barplot2(Y[2,], beside=T, plot.ci=TRUE, ci.l=Y_cil[2,], ci.u=Y_ciu[2,],
                main=paste0("Height = ",Hs[2],"m"), col=palette(), ylab=yvar)
  
  df1 <- as.data.frame(Y)
  df1$H <- Hs
  df2 <- as.data.frame(se)
  df2$H <- Hs
  df1 <- melt(df1, id="H", value.name=yvar, variable.name=pftvar)
  df2 <- melt(df2, id="H", value.name=paste0(yvar,"_SE"), variable.name=pftvar)  
  df <- merge(df1, df2)
  par(o)
  return(invisible(df))
}

```


### Leaf mass fraction and leaf area ratio by pft

#### LMF
```{r lmfpft}
gamplotandpred(dataset2, "pft", "lmlf_mso")
```

#### LAR
```{r larpft}
gamplotandpred(dataset2, "pft", "lalf_mso")
```

### Pipe model ratios by pft

#### Leaf mass pipe ratio
```{r pipemlfpft}
pipemlf <- gamplotandpred(dataset2, "pft", "lmlf_astbh", Hs=c(3,10))
```

#### Leaf area pipe ratio
```{r pipealfpft}
pipealf <- gamplotandpred(dataset2, "pft", "lalf_astbh", Hs=c(3,10))
```



```{r}
sla <- gamplotandpred(dataset2, "pft", "lsla", Hs=c(3,10))
```





```{r eval=FALSE}

dat <- subset(dataset2,!is.na(a.stbh) & !is.na(m.so))
datsp <- split(dat, dat$Group)
ii <- which(sapply(datsp,nrow) > 10)
lms <- lapply(datsp[ii],
              function(x)lm(log10(m.so) ~ log10(a.stbh), data=x))  
getr2 <- function(x)summary(x)$adj.r.squared

r2 <- sapply(lms, getr2)


```


```{r eval=FALSE}
lme1 <- lme(log10(m.so) ~ log10(a.stbh), random=~log10(a.stbh)|Group, 
            data=dataset2, subset=pft=="EG", na.action=na.omit)
lme2 <- lme(log10(m.so) ~ log10(a.stbh), random=~log10(a.stbh)|Group, 
            data=dataset2, subset=pft=="EA", na.action=na.omit)
lme3 <- lme(log10(m.so) ~ log10(a.stbh), random=~log10(a.stbh)|Group, 
            data=dataset2, subset=pft=="DA", na.action=na.omit)

datsp <- split(dataset2, dataset2$Group)
R <- sapply(datsp, function(x)range(x$a.stbh))

makedf <- function(x){
  
  p <- coef(x)
  g <- rownames(p)
  r <- R[,g]
  df <- as.data.frame(cbind(p,t(r)))
  names(df) <- c("a","b","xmin","xmax")
  
  return(df)
}

p <- makedf(lme1)
pointsp <- function(x,...){
  for(i in 1:nrow(x)){
    ablinepiece(x$a[i], x$b[i], from=log10(x$xmin[i]), to=log10(x$xmax[i]), ...)
  }
}
with(dataset2, plot(log10(a.stbh), log10(m.so), type='n'))
pointsp(makedf(lme1), col="red")
pointsp(makedf(lme2), col="green3")
pointsp(makedf(lme3), col="blue")


```




